# ============================================
# Configuración del Servidor
# ============================================
server.port=8080

# ============================================
# Configuración de MySQL
# ============================================
spring.datasource.url=jdbc:mysql://localhost:3306/incidentes_db?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ============================================
# Configuración de JPA / Hibernate
# ============================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ============================================
# Configuración JWT
# ============================================
jwt.secret=MiClaveSecretaSuperSeguraParaJWTIncidentesCiberseguridad2026ConAlMenos256BitsDeEntropiaParaHS256
jwt.expiration=86400000

# ============================================
# Configuración de Jackson
# ============================================
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
spring.jackson.time-zone=America/Bogota
